#!/usr/bin/env node
/**
 * Drafts a weekly devlog entry per repo from its merged PRs, using the local model.
 * Output is a DRAFT file for a human (or a Claude session) to verify before publishing —
 * this tool never pushes, comments or opens PRs.
 *
 *   local-worker-devlog --repo owner/name [--repo owner/other] [--days 7] [--out ./devlog-drafts] [--model gpt-oss:20b]
 */
import fs from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "node:util";
import { contextSize } from "./budget.js";
import { loadConfig, MODELS, type ModelName } from "./config.js";
import {
  buildDevlogInput,
  DEVLOG_INSTRUCTION,
  findMissingPrRefs,
  findUnknownPrRefs,
  isoWeekLabel,
  isPrListTruncated,
  listMergedPrs,
  PR_LIST_LIMIT,
} from "./devlog.js";
import { chat } from "./ollama.js";
import { resolveWritable, safeWriteFile } from "./paths.js";

const { values } = parseArgs({
  options: {
    repo: { type: "string", multiple: true },
    days: { type: "string", default: "7" },
    out: { type: "string", default: "devlog-drafts" },
    model: { type: "string" },
  },
});

const repos = values.repo ?? [];
if (repos.length === 0) {
  console.error("usage: local-worker-devlog --repo owner/name [--repo ...] [--days 7] [--out dir] [--model name]");
  process.exit(2);
}
const days = Number(values.days);
if (!Number.isInteger(days) || days < 1 || days > 90) {
  console.error(`--days must be an integer from 1 to 90, got "${values.days}"`);
  process.exit(2);
}
const config = loadConfig();
const model = (values.model ?? config.defaultModel) as ModelName;
if (!(MODELS as readonly string[]).includes(model)) {
  console.error(`--model must be one of ${MODELS.join(", ")}`);
  process.exit(2);
}

/** YYYY-MM-DD of the LOCAL calendar date, matching isoWeekLabel. */
const localDate = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

const now = new Date();
const since = localDate(new Date(now.getTime() - days * 86_400_000));
const week = isoWeekLabel(now);
const outDir = path.resolve(values.out);
await fs.mkdir(outDir, { recursive: true });

let failures = 0;
const written = new Set<string>();
for (const repo of repos) {
  try {
    const prs = await listMergedPrs(repo, since);
    if (prs.length === 0) {
      console.log(`${repo}: no PRs merged since ${since}, nothing to draft`);
      continue;
    }
    const user = `${DEVLOG_INSTRUCTION}\n\n${buildDevlogInput(repo, prs)}`;
    const r = await chat({ baseUrl: config.ollamaUrl, model, system: "You write concise, factual engineering notes.", user, numCtx: contextSize(user.length, config.maxCtx) });

    const unknown = findUnknownPrRefs(r.content, prs);
    const missing = findMissingPrRefs(r.content, prs);
    const warnings = [
      ...(isPrListTruncated(prs)
        ? [`more than ${PR_LIST_LIMIT} PRs were merged since ${since} and gh's list is capped, so some are missing from this draft; use a smaller --days`]
        : []),
      ...(unknown.length ? [`cites PRs that weren't in the input: ${unknown.map((n) => `#${n}`).join(", ")}`] : []),
      ...(missing.length ? [`never cites: ${missing.map((n) => `#${n}`).join(", ")}`] : []),
    ];
    const header = [
      `<!-- DRAFT generated by local-worker devlog (${model}, ${r.seconds.toFixed(0)}s) on ${localDate(now)}`,
      `     from ${prs.length} PRs merged in ${repo} since ${since}: ${prs.map((p) => `#${p.number}`).join(" ")}`,
      `     UNVERIFIED: check every bullet against its PR before publishing, then delete this comment.`,
      ...warnings.map((w) => `     WARNING: ${w}`),
      `-->`,
    ].join("\n");
    // owner-name-week, so alice/app and bob/app get separate files. Hyphens are legal in
    // both parts (a-b/c and a/b-c map to the same name), so never let one repo's draft
    // replace another's from the same run.
    const [owner, name] = repo.split("/") as [string, string];
    const file = path.join(outDir, `${owner}-${name}-${week}.md`);
    const key = file.toLowerCase();
    if (written.has(key)) throw new Error(`${file} was already written for another repo in this run`);
    written.add(key);
    // Same write path as the MCP tools, rooted at --out: no writing through a link planted
    // at the draft name, and the re-run of a week replaces its draft atomically.
    const target = await resolveWritable(file, [outDir], true);
    await safeWriteFile(target, `${header}\n\n# ${week}\n\n${r.content}\n`, { roots: [outDir], overwrite: true });
    console.log(`${repo}: wrote ${file} (${prs.length} PRs${warnings.length ? `, ${warnings.length} warning(s)` : ""})`);
  } catch (err) {
    failures++;
    console.error(`${repo}: ${err instanceof Error ? err.message : String(err)}`);
  }
}
process.exit(failures ? 1 : 0);
